config/routes.rb
Rails.application.routes.draw do


  resources :user
  resources :picture
  resources :recipient
  get 'static_pages/home'
  get  'static_pages/hi'
  root 'application#hello'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_many :recipient
    belongs_to :user
    validates :id, presence: true   
    validates :sent_date, presence: true
     validates :File_name, presence: true
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :user
    belongs_to :picture
    validates :name, presence: true
    validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :picture
    has_many :recipient
    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  def index
  end
end

app/controllers/recipient_controller.rb
class RecipientController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def hi
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/recipient_helper.rb
module RecipientHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Programateste</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/picture/index.html.erb
<h1>Picture#index</h1>
<p>Find me in app/views/picture/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Sent_date</th>
      <th>File_name</th>
    </tr>
  </thead>

<% @pictures.each do |pic| %>
  <tr>
    <td><%= pic.id %></td>
    <td><%= pic.sent_date %></td>
    <td><%= pic.file_name%></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/recipient/index.html.erb
<h1>Recipient#index</h1>
<p>Find me in app/views/recipient/index.html.erb</p>

app/views/static_pages/hi.html.erb
<h1>StaticPages#hi</h1>
<p>Find me in app/views/static_pages/hi.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th> Age</th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password%></td>
    <td><%= user.age%></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New User', new_user_path %>